linkListFile: "linkListFileName.txt"
linkListFileFolder: "C:\\Users\\nunot\\Documents\\_Documentos\\Projectos\\mass link downloder\\repositorio\\app\\"
downloadFolder: "C:\\Users\\nunot\\Documents\\_Documentos\\Projectos\\mass link downloder\\repositorio\\app\\downloaded_files"
